---
title: "Real Estate Analysis"
author: "sho"
date: "7/28/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data, include = FALSE, message = FALSE}

# Read data from Github to conduct analysis

library(RCurl)
library(readr)
library(dplyr)
library(purrr)
library(ggplot2)
library(tidyr)

url <- getURL("https://raw.githubusercontent.com/shohct/realestate/master/RealestateData.csv")
data <- read_csv(url)
```

## Preliminary EDA on real estate data

```{r EDA, echo = FALSE}
# Show data
print(data)

# Text review
data %>% 
  select(SoldPrice, AskingPrice, Bed, Sqft, Age, DaysOnMarket, PriceSqft) %>% 
  split(.$Bed) %>% 
  map(summary)

# Plot it
data %>% 
  mutate(Bed = factor(Bed)) %>% 
  pivot_longer(cols = c(SoldPrice, AskingPrice, Sqft, Age, DaysOnMarket, PriceSqft),
               names_to = "DataType",
               values_to = "Value") %>% 
  ggplot(aes(Bed, Value)) +
  geom_boxplot(aes(fill = Bed)) +
  facet_wrap(~DataType, scales = "free_y")
```

